// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createClinica = `-- name: CreateClinica :one
INSERT INTO clinicas (
    nome
) VALUES (
    $1
)
RETURNING id, nome
`

func (q *Queries) CreateClinica(ctx context.Context, nome string) (Clinica, error) {
	row := q.db.QueryRow(ctx, createClinica, nome)
	var i Clinica
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}
